// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: .proto

package com.itvillage.grpc.lib;

public interface HelloReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.itvillage.grpc.HelloReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   * @return The message.
   */
  String getMessage();
  /**
   * <code>string message = 1;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
